spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
#    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  application:
    name: user

server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

dis:
  app:
    jwtSecret: jwtDisSecretKey
    jwtExpiration: 86400
  notification:
    topic: /topic
    appPrefix: /app
    notificationEndpoint: /chat
    notificationBucket: ${dis.notification.topic}/messages

  spring:
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2000KB
        max-file-size: 15MB
        max-request-size: 25MB